let g:surround_obj_custom_objects = {
\   'u': { 'type': 'inline', 'delimiter': '_' },
\   'U': { 'type': 'inline', 'delimiter': '__' },
\ }

runtime! plugin/surround_obj.vim

function! s:test_surround_add() abort
  call s:do_test('yse"', 'foo bar baz', '"foo" bar baz')
  call s:do_test('wyse"', 'foo bar baz', 'foo "bar" baz')
  call s:do_test('ys$"', 'foo bar baz', '"foo bar baz"')

  call s:do_test('yse''', 'foo bar baz', '''foo'' bar baz')
  call s:do_test('wyse''', 'foo bar baz', 'foo ''bar'' baz')
  call s:do_test('ys$''', 'foo bar baz', '''foo bar baz''')

  call s:do_test('yseb', 'foo bar baz', '(foo) bar baz')
  call s:do_test('wyseb', 'foo bar baz', 'foo (bar) baz')
  call s:do_test('ys$b', 'foo bar baz', '(foo bar baz)')
  call s:do_test('ys$bwyseb', 'foo bar baz', '((foo) bar baz)')
  call s:do_test('wyseb', '  foo', '  (foo)')

  call s:do_test('yse)', 'foo bar baz', '( foo ) bar baz')
  call s:do_test('wyse)', 'foo bar baz', 'foo ( bar ) baz')
  call s:do_test('ys$)', 'foo bar baz', '( foo bar baz )')
  call s:do_test('ys$)wyse)', 'foo bar baz', '( ( foo ) bar baz )')
  call s:do_test('wyse)', '  foo', '  ( foo )')

  call s:do_test("ysetdiv\<CR>", 'foo bar baz', '<div>foo</div> bar baz')
  call s:do_test("wysetdiv\<CR>", 'foo bar baz', 'foo <div>bar</div> baz')
  call s:do_test("ys$tdiv\<CR>", 'foo bar baz', '<div>foo bar baz</div>')
  call s:do_test("ys$tdiv\<CR>wysetp\<CR>", 'foo bar baz', '<div><p>foo</p> bar baz</div>')
  call s:do_test("wysetdiv\<CR>", '  foo', '  <div>foo</div>')

  call s:do_test('ys$b..', '', '((()))')
  call s:do_test('ys$b..', 'foo', '(((foo)))')
endfunction

function! s:test_surround_change() abort
  call s:do_test('cs"b', '""', '()')
  call s:do_test('cs"b', '"foo"', '(foo)')
  call s:do_test('cs"b', '"foo "', '(foo )')
  call s:do_test('cs"b', '" foo"', '( foo)')
  call s:do_test('cs"b', '" foo "', '( foo )')
  call s:do_test('cs"b', '" \"foo\" "', '( \"foo\" )')
  call s:do_test('cs"b', '" \foo\ "', '( \foo\ )')
  call s:do_test('f"cs"b', '  "foo"  ', '  (foo)  ')

  call s:do_test('cs")', '""', '(  )')
  call s:do_test('cs")', '"foo"', '( foo )')
  call s:do_test('cs")', '"foo "', '( foo  )')
  call s:do_test('cs")', '" foo"', '(  foo )')
  call s:do_test('cs")', '" foo "', '(  foo  )')
  call s:do_test('cs")', '" \"foo\" "', '(  \"foo\"  )')
  call s:do_test('cs")', '" \foo\ "', '(  \foo\  )')
  call s:do_test('f"cs")', '  "foo"  ', '  ( foo )  ')

  call s:do_test('$cs"b', '""', '()')
  call s:do_test('$cs"b', '"foo"', '(foo)')
  call s:do_test('$cs"b', '"foo "', '(foo )')
  call s:do_test('$cs"b', '" foo"', '( foo)')
  call s:do_test('$cs"b', '" foo "', '( foo )')
  call s:do_test('$cs"b', '" \"foo\" "', '( \"foo\" )')
  call s:do_test('$cs"b', '" \foo\ "', '( \foo\ )')
  call s:do_test('2f"cs"b', '  "foo"  ', '  (foo)  ')

  call s:do_test('ffcs"b', '"foo"', '(foo)')
  call s:do_test('ffcs"b', '"foo "', '(foo )')
  call s:do_test('ffcs"b', '" foo"', '( foo)')
  call s:do_test('ffcs"b', '" foo "', '( foo )')
  call s:do_test('ffcs"b', '" \"foo\" "', '( \"foo\" )')
  call s:do_test('ffcs"b', '" \foo\ "', '( \foo\ )')
  call s:do_test('f"cs"b', '" \"foo\" "', '( \"foo\" )')
  call s:do_test('2f"cs"b', '" \"foo\" "', '( \"foo\" )')
  call s:do_test('ffcs"b', '  "foo"  ', '  (foo)  ')

  call s:do_test('cs"b', '"foo"bar"baz"', '(foo)bar"baz"')
  call s:do_test('ffcs"b', '"foo"bar"baz"', '(foo)bar"baz"')
  call s:do_test('f"cs"b', '"foo"bar"baz"', '(foo)bar"baz"')
  call s:do_test('2f"cs"b', '"foo"bar"baz"', '"foo"bar(baz)')
  call s:do_test('fbcs"b', '"foo"bar"baz"', '"foo(bar)baz"')
  call s:do_test('2fbcs"b', '"foo"bar"baz"', '"foo"bar(baz)')
  call s:do_test('$cs"b', '"foo"bar"baz"', '"foo"bar(baz)')

  call s:do_test('csbB', '()', '{}')
  call s:do_test('csbB', '(foo)', '{foo}')
  call s:do_test('csbB', '(foo )', '{foo }')
  call s:do_test('csbB', '( foo)', '{ foo}')
  call s:do_test('csbB', '( foo )', '{ foo }')
  call s:do_test('csbB', '(foo())', '{foo()}')
  call s:do_test('f(csbB', '(foo())', '(foo{})')
  call s:do_test('f(csbB', '  ()  ', '  {}  ')
  call s:do_test('f(csbB', '  (foo)  ', '  {foo}  ')

  call s:do_test('csbB', '( \(foo )', '{ \(foo }')
  call s:do_test('csbB', '( foo\) )', '{ foo\) }')
  call s:do_test('csbB', '( \(foo\) )', '{ \(foo\) }')

  call s:do_test('csbB', "(\na)", "{\na}")
  call s:do_test('csbB', "(a\n)", "{a\n}")
  call s:do_test('csbB', "((\na))", "{(\na)}")
  call s:do_test('csbB', "((a\n))", "{(a\n)}")

  call s:do_test('$csbB', '()', '{}')
  call s:do_test('$csbB', '(foo )', '{foo }')
  call s:do_test('$csbB', '( foo)', '{ foo}')
  call s:do_test('$csbB', '( foo )', '{ foo }')
  call s:do_test('$csbB', '(foo())', '{foo()}')
  call s:do_test('f)csbB', '(foo())', '(foo{})')
  call s:do_test('f)csbB', '  ()  ', '  {}  ')
  call s:do_test('f)csbB', '  (foo)  ', '  {foo}  ')

  call s:do_test('ffcsbB', '(foo)', '{foo}')
  call s:do_test('ffcsbB', '(foo )', '{foo }')
  call s:do_test('ffcsbB', '( foo)', '{ foo}')
  call s:do_test('ffcsbB', '( foo )', '{ foo }')
  call s:do_test('ffcsbB', '(foo())', '{foo()}')
  call s:do_test('ffcsbB', '  (foo)  ', '  {foo}  ')

  call s:do_test('csbB', '(foo)bar(baz)', '{foo}bar(baz)')
  call s:do_test('ffcsbB', '(foo)bar(baz)', '{foo}bar(baz)')
  call s:do_test('f)csbB', '(foo)bar(baz)', '{foo}bar(baz)')
  call s:do_test('f(csbB', '(foo)bar(baz)', '(foo)bar{baz}')
  call s:do_test('2fbcsbB', '(foo)bar(baz)', '(foo)bar{baz}')
  call s:do_test('$csbB', '(foo)bar(baz)', '(foo)bar{baz}')

  call s:do_test("csttp\<CR>", '<div></div>', '<p></p>')
  call s:do_test("csttp\<CR>", '<div>foo</div>', '<p>foo</p>')
  call s:do_test("csttp\<CR>", '<div>foo </div>', '<p>foo </p>')
  call s:do_test("csttp\<CR>", '<div> foo</div>', '<p> foo</p>')
  call s:do_test("csttp\<CR>", '<div> foo </div>', '<p> foo </p>')
  call s:do_test("csttp\<CR>", '<div>foo<b>bar</b></div>', '<p>foo<b>bar</b></p>')
  call s:do_test("f<cstti\<CR>", '<div>foo<b>bar</b></div>', '<div>foo<i>bar</i></div>')
  call s:do_test("f<csttp\<CR>", '  <div></div>  ', '  <p></p>  ')
  call s:do_test("f<csttp\<CR>", '  <div>foo</div>  ', '  <p>foo</p>  ')

  call s:do_test("f>csttp\<CR>", '<div></div>', '<p></p>')
  call s:do_test("f>csttp\<CR>", '<div>foo</div>', '<p>foo</p>')
  call s:do_test("f>csttp\<CR>", '<div>foo </div>', '<p>foo </p>')
  call s:do_test("f>csttp\<CR>", '<div> foo</div>', '<p> foo</p>')
  call s:do_test("f>csttp\<CR>", '<div> foo </div>', '<p> foo </p>')
  call s:do_test("f>csttp\<CR>", '<div>foo<b>bar</b></div>', '<p>foo<b>bar</b></p>')
  call s:do_test("2f>cstti\<CR>", '<div>foo<b>bar</b></div>', '<div>foo<i>bar</i></div>')
  call s:do_test("f>csttp\<CR>", '  <div></div>  ', '  <p></p>  ')
  call s:do_test("f>csttp\<CR>", '  <div>foo</div>  ', '  <p>foo</p>  ')

  call s:do_test("f<csttp\<CR>", '<div></div>', '<p></p>')
  call s:do_test("f<csttp\<CR>", '<div>foo</div>', '<p>foo</p>')
  call s:do_test("f<csttp\<CR>", '<div>foo </div>', '<p>foo </p>')
  call s:do_test("f<csttp\<CR>", '<div> foo</div>', '<p> foo</p>')
  call s:do_test("f<csttp\<CR>", '<div> foo </div>', '<p> foo </p>')
  call s:do_test("3f<csttp\<CR>", '<div>foo<b>bar</b></div>', '<p>foo<b>bar</b></p>')
  call s:do_test("f<cstti\<CR>", '<div>foo<b>bar</b></div>', '<div>foo<i>bar</i></div>')
  call s:do_test("f<csttp\<CR>", '  <div></div>  ', '  <p></p>  ')
  call s:do_test("f<csttp\<CR>", '  <div>foo</div>  ', '  <p>foo</p>  ')

  call s:do_test("$csttp\<CR>", '<div></div>', '<p></p>')
  call s:do_test("$csttp\<CR>", '<div>foo</div>', '<p>foo</p>')
  call s:do_test("$csttp\<CR>", '<div>foo </div>', '<p>foo </p>')
  call s:do_test("$csttp\<CR>", '<div> foo</div>', '<p> foo</p>')
  call s:do_test("$csttp\<CR>", '<div> foo </div>', '<p> foo </p>')
  call s:do_test("$csttp\<CR>", '<div>foo<b>bar</b></div>', '<p>foo<b>bar</b></p>')
  call s:do_test("2f>cstti\<CR>", '<div>foo<b>bar</b></div>', '<div>foo<i>bar</i></div>')
  call s:do_test("2f>csttp\<CR>", '  <div></div>  ', '  <p></p>  ')
  call s:do_test("2f>csttp\<CR>", '  <div>foo</div>  ', '  <p>foo</p>  ')
endfunction

function! s:test_surround_delete() abort
  call s:do_test('ds"', '""', '')
  call s:do_test('ds"', '"foo"', 'foo')
  call s:do_test('ds"', '"foo "', 'foo')
  call s:do_test('ds"', '" foo"', 'foo')
  call s:do_test('ds"', '" foo "', 'foo')
  call s:do_test('ds"', '" \"foo\" "', '\"foo\"')
  call s:do_test('ds"', '" \foo\ "', '\foo\')
  call s:do_test('f"ds"', '  "foo"  ', '  foo  ')

  call s:do_test('$ds"', '""', '')
  call s:do_test('$ds"', '"foo"', 'foo')
  call s:do_test('$ds"', '"foo "', 'foo')
  call s:do_test('$ds"', '" foo"', 'foo')
  call s:do_test('$ds"', '" foo "', 'foo')
  call s:do_test('$ds"', '" \"foo\" "', '\"foo\"')
  call s:do_test('$ds"', '" \foo\ "', '\foo\')
  call s:do_test('2f"ds"', '  "foo"  ', '  foo  ')

  call s:do_test('ffds"', '"foo"', 'foo')
  call s:do_test('ffds"', '"foo "', 'foo')
  call s:do_test('ffds"', '" foo"', 'foo')
  call s:do_test('ffds"', '" foo "', 'foo')
  call s:do_test('ffds"', '" \"foo\" "', '\"foo\"')
  call s:do_test('ffds"', '" \foo\ "', '\foo\')
  call s:do_test('ffds"', '  "foo"  ', '  foo  ')

  call s:do_test('ds"', '"foo"bar"baz"', 'foobar"baz"')
  call s:do_test('ffds"', '"foo"bar"baz"', 'foobar"baz"')
  call s:do_test('f"ds"', '"foo"bar"baz"', 'foobar"baz"')
  call s:do_test('2f"ds"', '"foo"bar"baz"', '"foo"barbaz')
  call s:do_test('fbds"', '"foo"bar"baz"', '"foobarbaz"')
  call s:do_test('2fbds"', '"foo"bar"baz"', '"foo"barbaz')
  call s:do_test('$ds"', '"foo"bar"baz"', '"foo"barbaz')

  call s:do_test('dsb', '()', '')
  call s:do_test('dsb', '(foo)', 'foo')
  call s:do_test('dsb', '(foo )', 'foo')
  call s:do_test('dsb', '( foo)', 'foo')
  call s:do_test('dsb', '( foo )', 'foo')
  call s:do_test('dsb', '(foo())', 'foo()')
  call s:do_test('f(dsb', '(foo())', '(foo)')
  call s:do_test('f(dsb', '  ()  ', '    ')
  call s:do_test('f(dsb', '  (foo)  ', '  foo  ')

  call s:do_test('ds)', '()', '')
  call s:do_test('ds)', '(foo)', 'foo')
  call s:do_test('ds)', '(foo )', 'foo')
  call s:do_test('ds)', '( foo)', 'foo')
  call s:do_test('ds)', '( foo )', 'foo')
  call s:do_test('ds)', '(foo())', 'foo()')
  call s:do_test('f(ds)', '(foo())', '(foo)')
  call s:do_test('f(ds)', '  ()  ', '    ')
  call s:do_test('f(ds)', '  (foo)  ', '  foo  ')

  call s:do_test('dsb', '( \(foo )', '\(foo')
  call s:do_test('dsb', '( foo\) )', 'foo\)')
  call s:do_test('dsb', '( \(foo\) )', '\(foo\)')

  call s:do_test('dsb', "(\na)", "\na")
  call s:do_test('dsb', "(a\n)", "a\n")
  call s:do_test('dsb', "((\na))", "(\na)")
  call s:do_test('dsb', "((a\n))", "(a\n)")

  call s:do_test('$dsb', '()', '')
  call s:do_test('$dsb', '(foo)', 'foo')
  call s:do_test('$dsb', '(foo )', 'foo')
  call s:do_test('$dsb', '( foo)', 'foo')
  call s:do_test('$dsb', '( foo )', 'foo')
  call s:do_test('$dsb', '(foo())', 'foo()')
  call s:do_test('f)dsb', '(foo())', '(foo)')
  call s:do_test('f)dsb', '  ()  ', '    ')
  call s:do_test('f)dsb', '  (foo)  ', '  foo  ')

  call s:do_test('ffdsb', '(foo)', 'foo')
  call s:do_test('ffdsb', '(foo )', 'foo')
  call s:do_test('ffdsb', '( foo)', 'foo')
  call s:do_test('ffdsb', '( foo )', 'foo')
  call s:do_test('ffdsb', '(foo())', 'foo()')
  call s:do_test('ffdsb', '  (foo)  ', '  foo  ')

  call s:do_test('dsbB', '(foo)bar(baz)', 'foobar(baz)')
  call s:do_test('ffdsbB', '(foo)bar(baz)', 'foobar(baz)')
  call s:do_test('f)dsbB', '(foo)bar(baz)', 'foobar(baz)')
  call s:do_test('f(dsbB', '(foo)bar(baz)', '(foo)barbaz')
  call s:do_test('2fbdsbB', '(foo)bar(baz)', '(foo)barbaz')
  call s:do_test('$dsbB', '(foo)bar(baz)', '(foo)barbaz')

  call s:do_test('dst', '<div></div>', '')
  call s:do_test('dst', '<div>foo</div>', 'foo')
  call s:do_test('dst', '<div>foo </div>', 'foo')
  call s:do_test('dst', '<div> foo</div>', 'foo')
  call s:do_test('dst', '<div> foo </div>', 'foo')
  call s:do_test('dst', '<div>foo<b>bar</b></div>', 'foo<b>bar</b>')
  call s:do_test('f<dst', '<div>foo<b>bar</b></div>', '<div>foobar</div>')
  call s:do_test('f<dst', '  <div></div>  ', '    ')
  call s:do_test('f<dst', '  <div>foo</div>  ', '  foo  ')

  call s:do_test('f>dst', '<div></div>', '')
  call s:do_test('f>dst', '<div>foo</div>', 'foo')
  call s:do_test('f>dst', '<div>foo </div>', 'foo')
  call s:do_test('f>dst', '<div> foo</div>', 'foo')
  call s:do_test('f>dst', '<div> foo </div>', 'foo')
  call s:do_test('f>dst', '<div>foo<b>bar</b></div>', 'foo<b>bar</b>')
  call s:do_test('2f>dst', '<div>foo<b>bar</b></div>', '<div>foobar</div>')
  call s:do_test('f>dst', '  <div></div>  ', '    ')
  call s:do_test('f>dst', '  <div>foo</div>  ', '  foo  ')

  call s:do_test('f<dst', '<div></div>', '')
  call s:do_test('f<dst', '<div>foo</div>', 'foo')
  call s:do_test('f<dst', '<div>foo </div>', 'foo')
  call s:do_test('f<dst', '<div> foo</div>', 'foo')
  call s:do_test('f<dst', '<div> foo </div>', 'foo')
  call s:do_test('3f<dst', '<div>foo<b>bar</b></div>', 'foo<b>bar</b>')
  call s:do_test('2f<dst', '<div>foo<b>bar</b></div>', '<div>foobar</div>')
  call s:do_test('2f<dst', '  <div></div>  ', '    ')
  call s:do_test('2f<dst', '  <div>foo</div>  ', '  foo  ')

  call s:do_test('$dst', '<div></div>', '')
  call s:do_test('$dst', '<div>foo</div>', 'foo')
  call s:do_test('$dst', '<div>foo </div>', 'foo')
  call s:do_test('$dst', '<div> foo</div>', 'foo')
  call s:do_test('$dst', '<div> foo </div>', 'foo')
  call s:do_test('$dst', '<div>foo<b>bar</b></div>', 'foo<b>bar</b>')
  call s:do_test('3f>dst', '<div>foo<b>bar</b></div>', '<div>foobar</div>')
  call s:do_test('2f>dst', '  <div></div>  ', '    ')

  call s:do_test("/foo\<CR>dst", '<div>foo</div>', 'foo')
  call s:do_test("/foo\<CR>dst", '<div>foo </div>', 'foo')
  call s:do_test("/foo\<CR>dst", '<div> foo</div>', 'foo')
  call s:do_test("/foo\<CR>dst", '<div> foo </div>', 'foo')
  call s:do_test("/foo\<CR>dst", '<div>foo<b>bar</b></div>', 'foo<b>bar</b>')
  call s:do_test("/bar\<CR>dst", '<div>foo<b>bar</b></div>', '<div>foobar</div>')
  call s:do_test("/foo\<CR>dst", '  <div>foo</div>  ', '  foo  ')
endfunction

function! s:test_surround_textobj() abort
  call s:do_test("d\<Plug>(surround-obj-a:u)", '_A_', '')
  call s:do_test("$d\<Plug>(surround-obj-a:u)", '_A_', '')
  call s:do_test("d\<Plug>(surround-obj-a:u)", ' _A_ ', ' _A_ ')
  call s:do_test("$d\<Plug>(surround-obj-a:u)", ' _A_ ', ' _A_ ')
  call s:do_test("fAd\<Plug>(surround-obj-a:u)", ' _A_ ', '  ')
  call s:do_test("d\<Plug>(surround-obj-a:u)", '_A__B_', '_B_')
  call s:do_test("$d\<Plug>(surround-obj-a:u)", '_A__B_', '_A_')
  call s:do_test("fAd\<Plug>(surround-obj-a:u)", '_A__B_', '_B_')
  call s:do_test("fBd\<Plug>(surround-obj-a:u)", '_A__B_', '_A_')

  call s:do_test("d\<Plug>(surround-obj-i:u)", '_A_', '__')
  call s:do_test("$d\<Plug>(surround-obj-i:u)", '_A_', '__')
  call s:do_test("d\<Plug>(surround-obj-i:u)", ' _A_ ', ' _A_ ')
  call s:do_test("$d\<Plug>(surround-obj-i:u)", ' _A_ ', ' _A_ ')
  call s:do_test("fAd\<Plug>(surround-obj-i:u)", ' _A_ ', ' __ ')
  call s:do_test("d\<Plug>(surround-obj-i:u)", '_A__B_', '___B_')
  call s:do_test("$d\<Plug>(surround-obj-i:u)", '_A__B_', '_A___')
  call s:do_test("fAd\<Plug>(surround-obj-i:u)", '_A__B_', '___B_')
  call s:do_test("fBd\<Plug>(surround-obj-i:u)", '_A__B_', '_A___')

  call s:do_test("d\<Plug>(surround-obj-a:U)", '__A__', '')
  call s:do_test("$d\<Plug>(surround-obj-a:U)", '__A__', '')
  call s:do_test("d\<Plug>(surround-obj-a:U)", ' __A__ ', ' __A__ ')
  call s:do_test("$d\<Plug>(surround-obj-a:U)", ' __A__ ', ' __A__ ')
  call s:do_test("fAd\<Plug>(surround-obj-a:U)", ' __A__ ', '  ')

  call s:do_test("d\<Plug>(surround-obj-i:U)", '__A__', '____')
  call s:do_test("$d\<Plug>(surround-obj-i:U)", '__A__', '____')
  call s:do_test("d\<Plug>(surround-obj-i:U)", ' __A__ ', ' __A__ ')
  call s:do_test("$d\<Plug>(surround-obj-i:U)", ' __A__ ', ' __A__ ')
  call s:do_test("fAd\<Plug>(surround-obj-i:U)", ' __A__ ', ' ____ ')

  call s:do_test("d\<Plug>(surround-obj-a:t)", '<div>A</div>', '')
  call s:do_test("$d\<Plug>(surround-obj-a:t)", '<div>A</div>', '')
  call s:do_test("d\<Plug>(surround-obj-a:t)", ' <div>A</div> ', ' <div>A</div> ')
  call s:do_test("$d\<Plug>(surround-obj-a:t)", ' <div>A</div> ', ' <div>A</div> ')
  call s:do_test("fAd\<Plug>(surround-obj-a:t)", ' <div>A</div> ', '  ')
  call s:do_test("d\<Plug>(surround-obj-a:t)", '<div>A<div>B</div>C</div>', '')
  call s:do_test("$d\<Plug>(surround-obj-a:t)", '<div>A<div>B</div>C</div>', '')
  call s:do_test("fAd\<Plug>(surround-obj-a:t)", '<div>A<div>B</div>C</div>', '')
  call s:do_test("fBd\<Plug>(surround-obj-a:t)", '<div>A<div>B</div>C</div>', '<div>AC</div>')
  call s:do_test("fCd\<Plug>(surround-obj-a:t)", '<div>A<div>B</div>C</div>', '')

  call s:do_test("d\<Plug>(surround-obj-i:t)", '<div>A</div>', '<div></div>')
  call s:do_test("$d\<Plug>(surround-obj-i:t)", '<div>A</div>', '<div></div>')
  call s:do_test("d\<Plug>(surround-obj-i:t)", ' <div>A</div> ', ' <div>A</div> ')
  call s:do_test("$d\<Plug>(surround-obj-i:t)", ' <div>A</div> ', ' <div>A</div> ')
  call s:do_test("fAd\<Plug>(surround-obj-i:t)", ' <div>A</div> ', ' <div></div> ')
  call s:do_test("d\<Plug>(surround-obj-i:t)", '<div>A<div>B</div>C</div>', '<div></div>')
  call s:do_test("$d\<Plug>(surround-obj-i:t)", '<div>A<div>B</div>C</div>', '<div></div>')
  call s:do_test("fAd\<Plug>(surround-obj-i:t)", '<div>A<div>B</div>C</div>', '<div></div>')
  call s:do_test("fBd\<Plug>(surround-obj-i:t)", '<div>A<div>B</div>C</div>', '<div>A<div></div>C</div>')
  call s:do_test("fCd\<Plug>(surround-obj-i:t)", '<div>A<div>B</div>C</div>', '<div></div>')
endfunction

function! s:do_test(key_strokes, source, expected_result) abort
  new
  map <buffer> ys  <Plug>(surround-obj-add)
  nmap <buffer> cs  <Plug>(surround-obj-change)
  nmap <buffer> ds  <Plug>(surround-obj-delete)
  silent put =a:source
  normal! ggdd0
  0verbose call feedkeys(a:key_strokes, 'x')
  call assert_equal(a:expected_result, join(getline(1, line('$')), "\n"))
  close!
endfunction
